[project]
name = "vamp"
channels = ["conda-forge"]
description = "VAMP planner environment managed by pixi"

[dependencies]
python = "*"
eigen = "*"
clang = "*"
clangxx = "*"
lld = "*"
llvm-tools = "*"
libstdcxx-ng = "*"

[system-dependencies]
apt = [
  "build-essential",
  "libeigen3-dev",
  "git",
  "wget",
  "ca-certificates",
  "curl",
  "lsb-release",
  "gnupg2",
  "python3-pip",
  "make",
  "gcc",
  "g++",
  "libasound2",
  "pkg-config"
]

[pypi-dependencies]
numpy = "*"
tabulate = "*"
fire = "*"
pandas = "*"
xmltodict = "*"
pybullet = "*"
ompl = "*"

[tasks]
run-evaluate-mbm = "python scripts/evaluate_mbm.py"
run-visualize-mbm = "python scripts/visualize_mbm.py"
run-sphere-cage-example = "python scripts/sphere_cage_example.py"
run-attachments = "python scripts/attachments.py"
run-flying-sphere = "python scripts/flying_sphere.py"
run-visualize-ompl = "python scripts/visualize_ompl.py"
